<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::insert([
            ['id' => 1, 'name' => 'Colombia'],
            ['id' => 2, 'name' => 'Ecuador'],
            ['id' => 3, 'name' => 'Perú'],
            ['id' => 4, 'name' => 'Afganistán'],
            ['id' => 5, 'name' => 'Albania'],
            ['id' => 6, 'name' => 'Alemania'],
            ['id' => 7, 'name' => 'Angola'],
            ['id' => 8, 'name' => 'Arabia Saudita'],
            ['id' => 9, 'name' => 'Argelia'],
            ['id' => 10, 'name' => 'Argentina'],
            ['id' => 11, 'name' => 'Armenia'],
            ['id' => 12, 'name' => 'Australia'],
            ['id' => 13, 'name' => 'Austria'],
            ['id' => 14, 'name' => 'Azerbaiyán'],
            ['id' => 15, 'name' => 'Bahamas'],
            ['id' => 16, 'name' => 'Bangladés'],
            ['id' => 17, 'name' => 'Barbados'],
            ['id' => 18, 'name' => 'Baréin'],
            ['id' => 19, 'name' => 'Bélgica'],
            ['id' => 20, 'name' => 'Belice'],
            ['id' => 21, 'name' => 'Benín'],
            ['id' => 22, 'name' => 'Bielorrusia'],
            ['id' => 23, 'name' => 'Bolivia'],
            ['id' => 24, 'name' => 'Bonaire, San Eustaquio Y Saba'],
            ['id' => 25, 'name' => 'Bosnia-Herzegovina'],
            ['id' => 26, 'name' => 'Botsuana'],
            ['id' => 27, 'name' => 'Brasil'],
            ['id' => 28, 'name' => 'Brunéi'],
            ['id' => 29, 'name' => 'Bulgaria'],
            ['id' => 30, 'name' => 'Burkina Faso'],
            ['id' => 31, 'name' => 'Burundi'],
            ['id' => 32, 'name' => 'Bután'],
            ['id' => 33, 'name' => 'Cabo Verde'],
            ['id' => 34, 'name' => 'Camboya'],
            ['id' => 35, 'name' => 'Camerún'],
            ['id' => 36, 'name' => 'Canadá'],
            ['id' => 37, 'name' => 'Chad'],
            ['id' => 38, 'name' => 'Chile'],
            ['id' => 39, 'name' => 'China'],
            ['id' => 40, 'name' => 'Chipre'],
            ['id' => 41, 'name' => 'Comoras'],
            ['id' => 42, 'name' => 'Congo'],
            ['id' => 43, 'name' => 'Corea Del Norte'],
            ['id' => 44, 'name' => 'Corea Del Sur'],
            ['id' => 45, 'name' => 'Costa De Marfil'],
            ['id' => 46, 'name' => 'Costa Rica'],
            ['id' => 47, 'name' => 'Croacia'],
            ['id' => 48, 'name' => 'Cuba'],
            ['id' => 49, 'name' => 'Curazao'],
            ['id' => 50, 'name' => 'Dinamarca'],
            ['id' => 51, 'name' => 'Dominica'],
            ['id' => 52, 'name' => 'Egipto'],
            ['id' => 53, 'name' => 'El Salvador'],
            ['id' => 54, 'name' => 'Emiratos Árabes Unidos'],
            ['id' => 55, 'name' => 'Eritrea'],
            ['id' => 56, 'name' => 'Eslovaquia'],
            ['id' => 57, 'name' => 'Eslovenia'],
            ['id' => 58, 'name' => 'España'],
            ['id' => 59, 'name' => 'Estados Unidos'],
            ['id' => 60, 'name' => 'Estonia'],
            ['id' => 61, 'name' => 'Etiopía'],
            ['id' => 62, 'name' => 'Filipinas'],
            ['id' => 63, 'name' => 'Finlandia'],
            ['id' => 64, 'name' => 'Fiyi'],
            ['id' => 65, 'name' => 'Francia'],
            ['id' => 66, 'name' => 'Gabón'],
            ['id' => 67, 'name' => 'Gambia'],
            ['id' => 68, 'name' => 'Georgia'],
            ['id' => 69, 'name' => 'Ghana'],
            ['id' => 70, 'name' => 'Grecia'],
            ['id' => 71, 'name' => 'Groenlandia'],
            ['id' => 72, 'name' => 'Guadalupe'],
            ['id' => 73, 'name' => 'Guam'],
            ['id' => 74, 'name' => 'Guatemala'],
            ['id' => 75, 'name' => 'Guayana Francesa'],
            ['id' => 76, 'name' => 'Guernsey'],
            ['id' => 77, 'name' => 'Guinea'],
            ['id' => 78, 'name' => 'Guinea Ecuatorial'],
            ['id' => 79, 'name' => 'Guinea-Bisáu'],
            ['id' => 80, 'name' => 'Guyana'],
            ['id' => 81, 'name' => 'Haití'],
            ['id' => 82, 'name' => 'Honduras'],
            ['id' => 83, 'name' => 'Hong Kong'],
            ['id' => 84, 'name' => 'Hungría'],
            ['id' => 85, 'name' => 'India'],
            ['id' => 86, 'name' => 'Indonesia'],
            ['id' => 87, 'name' => 'Irak'],
            ['id' => 88, 'name' => 'Irán'],
            ['id' => 89, 'name' => 'Irlanda'],
            ['id' => 90, 'name' => 'Islandia'],
            ['id' => 91, 'name' => 'Israel'],
            ['id' => 92, 'name' => 'Italia'],
            ['id' => 93, 'name' => 'Jamaica'],
            ['id' => 94, 'name' => 'Japón'],
            ['id' => 95, 'name' => 'Jersey'],
            ['id' => 96, 'name' => 'Jordania'],
            ['id' => 97, 'name' => 'Kazajistán'],
            ['id' => 98, 'name' => 'Kenia'],
            ['id' => 99, 'name' => 'Kirguistán'],
            ['id' => 100, 'name' => 'Kuwait'],
            ['id' => 101, 'name' => 'Laos'],
            ['id' => 102, 'name' => 'Lesoto'],
            ['id' => 103, 'name' => 'Letonia'],
            ['id' => 104, 'name' => 'Líbano'],
            ['id' => 105, 'name' => 'Liberia'],
            ['id' => 106, 'name' => 'Libia'],
            ['id' => 107, 'name' => 'Liechtenstein'],
            ['id' => 108, 'name' => 'Lituania'],
            ['id' => 109, 'name' => 'Luxemburgo'],
            ['id' => 110, 'name' => 'Macedonia, La Antigua Republicayugoslava De'],
            ['id' => 111, 'name' => 'Madagascar'],
            ['id' => 112, 'name' => 'Malasia'],
            ['id' => 113, 'name' => 'Malaui'],
            ['id' => 114, 'name' => 'Maldivas'],
            ['id' => 115, 'name' => 'Malí'],
            ['id' => 116, 'name' => 'Malta'],
            ['id' => 117, 'name' => 'Marruecos'],
            ['id' => 118, 'name' => 'Martinica'],
            ['id' => 119, 'name' => 'Mauricio'],
            ['id' => 120, 'name' => 'Mauritania'],
            ['id' => 121, 'name' => 'Mayotte'],
            ['id' => 122, 'name' => 'México'],
            ['id' => 123, 'name' => 'Moldavia'],
            ['id' => 124, 'name' => 'Mónaco'],
            ['id' => 125, 'name' => 'Mongolia'],
            ['id' => 126, 'name' => 'Montenegro'],
            ['id' => 127, 'name' => 'Mozambique'],
            ['id' => 128, 'name' => 'Namibia'],
            ['id' => 129, 'name' => 'Nauru'],
            ['id' => 130, 'name' => 'Nepal'],
            ['id' => 131, 'name' => 'Nicaragua'],
            ['id' => 132, 'name' => 'Níger'],
            ['id' => 133, 'name' => 'Nigeria'],
            ['id' => 134, 'name' => 'Niue'],
            ['id' => 135, 'name' => 'Noruega'],
            ['id' => 136, 'name' => 'Nueva Caledonia'],
            ['id' => 137, 'name' => 'Nueva Zelanda'],
            ['id' => 138, 'name' => 'Omán'],
            ['id' => 139, 'name' => 'Países Bajos'],
            ['id' => 140, 'name' => 'Pakistán'],
            ['id' => 141, 'name' => 'Palaos'],
            ['id' => 142, 'name' => 'Palestina'],
            ['id' => 143, 'name' => 'Panamá'],
            ['id' => 144, 'name' => 'Papúa Nueva Guinea'],
            ['id' => 145, 'name' => 'Paraguay'],
            ['id' => 146, 'name' => 'Pitcairn'],
            ['id' => 147, 'name' => 'Polinesia Francesa'],
            ['id' => 148, 'name' => 'Polonia'],
            ['id' => 149, 'name' => 'Portugal'],
            ['id' => 150, 'name' => 'Puerto Rico'],
            ['id' => 151, 'name' => 'Qatar'],
            ['id' => 152, 'name' => 'Reino Unido'],
            ['id' => 153, 'name' => 'República Centroafricana'],
            ['id' => 154, 'name' => 'República Checa'],
            ['id' => 155, 'name' => 'República Democrática Del Congo'],
            ['id' => 156, 'name' => 'República Dominicana'],
            ['id' => 157, 'name' => 'Ruanda'],
            ['id' => 158, 'name' => 'Rumania'],
            ['id' => 159, 'name' => 'Rusia'],
            ['id' => 160, 'name' => 'Sahara Occidental'],
            ['id' => 161, 'name' => 'Samoa'],
            ['id' => 162, 'name' => 'Samoa Americana'],
            ['id' => 163, 'name' => 'San Bartolome'],
            ['id' => 164, 'name' => 'San Cristóbal Y Nieves'],
            ['id' => 165, 'name' => 'San Marino'],
            ['id' => 166, 'name' => 'San Martin (Parte Francesa)'],
            ['id' => 167, 'name' => 'San Pedro Y Miquelon'],
            ['id' => 168, 'name' => 'San Vicente Y Las Granadinas'],
            ['id' => 169, 'name' => 'Santa Helena, Ascension Y Tristan De Acuña'],
            ['id' => 170, 'name' => 'Santa Lucía'],
            ['id' => 171, 'name' => 'Santo Tomé Y Príncipe'],
            ['id' => 172, 'name' => 'Senegal'],
            ['id' => 173, 'name' => 'Serbia'],
            ['id' => 174, 'name' => 'Seychelles'],
            ['id' => 175, 'name' => 'Sierra Leona'],
            ['id' => 176, 'name' => 'Singapur'],
            ['id' => 177, 'name' => 'Sint Maarten (Parte Neerlandesa)'],
            ['id' => 178, 'name' => 'Siria'],
            ['id' => 179, 'name' => 'Somalia'],
            ['id' => 180, 'name' => 'Sri Lanka'],
            ['id' => 181, 'name' => 'Suazilandia'],
            ['id' => 182, 'name' => 'Sudáfrica'],
            ['id' => 183, 'name' => 'Sudán'],
            ['id' => 184, 'name' => 'Sudán Del Sur'],
            ['id' => 185, 'name' => 'Suecia'],
            ['id' => 186, 'name' => 'Suiza'],
            ['id' => 187, 'name' => 'Surinam'],
            ['id' => 188, 'name' => 'Svalbard Y Jan Mayen'],
            ['id' => 189, 'name' => 'Tailandia'],
            ['id' => 190, 'name' => 'Taiwán'],
            ['id' => 191, 'name' => 'Tanzania'],
            ['id' => 192, 'name' => 'Tayikistán'],
            ['id' => 193, 'name' => 'Territorio Britanico Del Oceano Indico'],
            ['id' => 194, 'name' => 'Territorios Australes Franceses'],
            ['id' => 195, 'name' => 'Timor Oriental'],
            ['id' => 196, 'name' => 'Togo'],
            ['id' => 197, 'name' => 'Tokelau'],
            ['id' => 198, 'name' => 'Tonga'],
            ['id' => 199, 'name' => 'Trinidad Y Tobago'],
            ['id' => 200, 'name' => 'Túnez'],
            ['id' => 201, 'name' => 'Turkmenistán'],
            ['id' => 202, 'name' => 'Turquía'],
            ['id' => 203, 'name' => 'Tuvalu'],
            ['id' => 204, 'name' => 'Ucrania'],
            ['id' => 205, 'name' => 'Uganda'],
            ['id' => 206, 'name' => 'Uruguay'],
            ['id' => 207, 'name' => 'Uzbekistán'],
            ['id' => 208, 'name' => 'Vanuatu'],
            ['id' => 209, 'name' => 'Vaticano'],
            ['id' => 210, 'name' => 'Venezuela'],
            ['id' => 211, 'name' => 'Vietnam'],
            ['id' => 212, 'name' => 'Wallis Y Futuna'],
            ['id' => 213, 'name' => 'Yemen'],
            ['id' => 214, 'name' => 'Yibuti'],
            ['id' => 215, 'name' => 'Zambia'],
            ['id' => 216, 'name' => 'Zimbabue'],
            ['id' => 217, 'name' => 'Aruba'],
            ['id' => 218, 'name' => 'Antigua y Barbuda'],
            ['id' => 219, 'name' => 'Islas Caimán'],
            ['id' => 220, 'name' => 'Islas Vírgenes Británicas'],

        ]);
    }
}
